### ISSUE TITLE
оформить методы либо по REST либо по другому типу

### ISSUE THREAD

**Issue by ololosha228** [xelaj/birch#1]
методы не удовлетворяют правилам RESTful API, которое было заявлено изначально.
нужно переделать названия всех методов целиком. оформить в едином стиле, (можно подумать над GraphQL, XML-RPC, JSON-RPC, можно ими не ограничиваться)

**Comment by RemiZOffAlex** [comment]
JSON-RPC можно попробовать с библиотекой flask_jsonrpc

**Comment by ololosha228** [comment]
закрываю таск, т.к. нет времени заниматься этим проектом, а таск закреплен за мной.
