### ISSUE TITLE
сделать парсер аргументов http запросов

### ISSUE THREAD

**Issue by ololosha228** [xelaj/birch#2]
сабж. reqparse не гибкий ни разу, и не удобен в целом.
как вариант, urllib.parse можно, но надо проверить в работе

**Comment by RemiZOffAlex** [comment]
Александр Ремизов, [16.08.18 03:18]
if args['full_order_list'] is None:
            args['full_order_list'] = False
Эм-м-м... Ну так себе

nn, [16.08.18 03:18]
[В ответ на Александр Ремизов]
а, ну вот, да

nn, [16.08.18 03:18]
[В ответ на Александр Ремизов]
это где я такое написал?)

Александр Ремизов, [16.08.18 03:18]
https://github.com/xelaj/birch/blob/master/birch/methods/invoices.py
строка 69

nn, [16.08.18 03:19]
[В ответ на Александр Ремизов]
ага, нашел, сяп.

по хорошему, нужно написать свой парсер аргументов. есть простейший в urllib, но он не очень все же

Александр Ремизов, [16.08.18 03:30]
https://github.com/xelaj/birch/issues/2 что имеется в виду?

Александр Ремизов, [16.08.18 03:31]
Можно попробовать wtforms  с валидацией

nn, [16.08.18 03:31]
[В ответ на nn]
это
